"""baseline schema

Revision ID: 1617a7836c31
Revises:
Create Date: 2026-07-04 20:41:05.560083
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1617a7836c31"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portals")),
        sa.UniqueConstraint("slug", name=op.f("uq_portals_slug")),
    )
    op.create_table(
        "properties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=True),
        sa.Column("listing_type", sa.String(length=16), nullable=False),
        sa.Column("property_type", sa.String(length=24), nullable=False),
        sa.Column("land_type", sa.String(length=24), nullable=True),
        sa.Column("province_ine", sa.String(length=2), nullable=False),
        sa.Column("municipality_ine", sa.String(length=5), nullable=True),
        sa.Column("municipality_name", sa.String(length=200), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("postal_code", sa.String(length=5), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("price_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column("area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("plot_area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_per_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("media", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_properties_fingerprint")),
    )
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.create_index("ix_properties_land_type", ["land_type"], unique=False)
        batch_op.create_index(
            "ix_properties_prov_price", ["province_ine", "price_amount"], unique=False
        )
        batch_op.create_index(
            "ix_properties_prov_type_listing",
            ["province_ine", "property_type", "listing_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_properties_type_ppm2", ["property_type", "price_per_m2"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "notification_channels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel_type", sa.String(length=24), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_channels_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channels")),
    )
    op.create_table(
        "portal_listings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portal_id"],
            ["portals.id"],
            name=op.f("fk_portal_listings_portal_id_portals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_portal_listings_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portal_listings")),
        sa.UniqueConstraint("portal_id", "external_id", name="portal_external_id"),
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("price_currency", sa.String(length=3), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_price_history_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
    )
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_price_history_property_time", ["property_id", "observed_at"], unique=False
        )

    op.create_table(
        "search_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("frequency_seconds", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "frequency_seconds >= 60", name=op.f("ck_search_alerts_frequency_min_60s")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_search_alerts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_alerts")),
    )
    with op.batch_alter_table("search_alerts", schema=None) as batch_op:
        batch_op.create_index("ix_search_alerts_due", ["is_active", "last_run_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_alerts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "search_cache",
        sa.Column("query_signature", sa.String(length=64), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.Column("result_ref", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portal_id"],
            ["portals.id"],
            name=op.f("fk_search_cache_portal_id_portals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("query_signature", name=op.f("pk_search_cache")),
    )
    op.create_table(
        "search_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.Column("query_signature", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("listings_found", sa.Integer(), nullable=False),
        sa.Column("listings_new", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portal_id"],
            ["portals.id"],
            name=op.f("fk_search_executions_portal_id_portals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_executions")),
    )
    with op.batch_alter_table("search_executions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_search_executions_portal_time", ["portal_id", "started_at"], unique=False
        )

    op.create_table(
        "alert_conditions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("parent_group_id", sa.Uuid(), nullable=True),
        sa.Column("node_type", sa.String(length=16), nullable=False),
        sa.Column("group_operator", sa.String(length=8), nullable=True),
        sa.Column("field_key", sa.String(length=128), nullable=True),
        sa.Column("operator", sa.String(length=16), nullable=True),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(node_type = 'CONDITION' AND field_key IS NOT NULL AND operator IS NOT NULL AND group_operator IS NULL) OR (node_type = 'GROUP' AND group_operator IS NOT NULL AND field_key IS NULL AND operator IS NULL)",
            name=op.f("ck_alert_conditions_node_shape_valid"),
        ),
        sa.CheckConstraint(
            "node_type in ('GROUP', 'CONDITION')", name=op.f("ck_alert_conditions_node_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["search_alerts.id"],
            name=op.f("fk_alert_conditions_alert_id_search_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_group_id"],
            ["alert_conditions.id"],
            name=op.f("fk_alert_conditions_parent_group_id_alert_conditions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_conditions")),
    )
    with op.batch_alter_table("alert_conditions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alert_conditions_tree", ["alert_id", "parent_group_id", "position"], unique=False
        )

    op.create_table(
        "alert_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["search_alerts.id"],
            name=op.f("fk_alert_matches_alert_id_search_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_alert_matches_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_matches")),
        sa.UniqueConstraint("alert_id", "property_id", name="alert_property_unique"),
    )
    with op.batch_alter_table("alert_matches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alert_matches_status_time", ["status", "matched_at"], unique=False
        )

    op.create_table(
        "alert_subscription_portals",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["search_alerts.id"],
            name=op.f("fk_alert_subscription_portals_alert_id_search_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portal_id"],
            ["portals.id"],
            name=op.f("fk_alert_subscription_portals_portal_id_portals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "alert_id", "portal_id", name=op.f("pk_alert_subscription_portals")
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channels.id"],
            name=op.f("fk_notifications_channel_id_notification_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["alert_matches.id"],
            name=op.f("fk_notifications_match_id_alert_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_status_time", ["status", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_status_time")

    op.drop_table("notifications")
    op.drop_table("alert_subscription_portals")
    with op.batch_alter_table("alert_matches", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_matches_status_time")

    op.drop_table("alert_matches")
    with op.batch_alter_table("alert_conditions", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_conditions_tree")

    op.drop_table("alert_conditions")
    with op.batch_alter_table("search_executions", schema=None) as batch_op:
        batch_op.drop_index("ix_search_executions_portal_time")

    op.drop_table("search_executions")
    op.drop_table("search_cache")
    with op.batch_alter_table("search_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_alerts_user_id"))
        batch_op.drop_index("ix_search_alerts_due")

    op.drop_table("search_alerts")
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.drop_index("ix_price_history_property_time")

    op.drop_table("price_history")
    op.drop_table("portal_listings")
    op.drop_table("notification_channels")
    op.drop_table("users")
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.drop_index("ix_properties_type_ppm2")
        batch_op.drop_index("ix_properties_prov_type_listing")
        batch_op.drop_index("ix_properties_prov_price")
        batch_op.drop_index("ix_properties_land_type")

    op.drop_table("properties")
    op.drop_table("portals")
    # ### end Alembic commands ###
