"""search execution normalization issues count

Revision ID: 6751a66ff70f
Revises: 1617a7836c31
Create Date: 2026-07-10 10:23:25.411395
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6751a66ff70f"
down_revision: str | None = "1617a7836c31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows (0 issues, since none were tracked before this
    # migration) — a NOT NULL column added without one fails against any table that already has
    # rows.
    with op.batch_alter_table("search_executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("normalization_issues", sa.Integer(), nullable=False, server_default="0")
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_executions", schema=None) as batch_op:
        batch_op.drop_column("normalization_issues")

    # ### end Alembic commands ###
